#! /bin/sh

### BEGIN INIT INFO
# Provides:		gitlab-autopupl
# Required-Start:
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:	
# Short-Description:	Gitlab Autopull Daemon
### END INIT INFO


# /etc/init.d/gitlab-autopull: start and stop Gitlab Autopull Daemon

. /lib/lsb/init-functions

GAD=/home/diddi/git/gitlab-autopull/git-autopull.pl
GAD_PID=/var/run/gitlab-autopull.pid

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_daemon_msg "Starting Gitlab Autopull Daemon" "gitlab-autopull" || true
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/sshd.pid --exec $GAD; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping Gitlab Autopull Daemon" "gitlab-autopull"|| true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/gitlab-autopull.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting Gitlab Autopull Daemon" "gitlab-autopull" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $GAD_PID
	if start-stop-daemon --start --quiet --oknodo --pidfile $GAD_PID --exec $GAD ; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
	status_of_proc -p $GAD_PID $GAD gitlab-autopull && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/gitlab-autopull {start|stop|restart|status}" || true
	exit 1
esac

exit 0
